### ISSUE TITLE
Game does not show the secret word after loss

### ISSUE THREAD

**Issue by BlehMaks** [Ivmin239/Hangman#2]
I would like to see the word that was in the game after I lost, but it is not showed in the end.

Could you please add this feature?

Thank you in advance!

**Comment by Ivmin239** [comment]
Hello!
So I have added this and some other feature.
Now issue is cleared!
Sorry for delay.

**Comment by BlehMaks** [comment]
So then push it here then please :)
no need to apologise, all good.
